// Global variables to get the uuids that are generated.
var uuid_1, uuid_2, uuid_3, uuid_4;

function generate() {
    // Clear result text
    document.getElementById("result").innerHTML = "Writing manifest ...";
    if (document.getElementById("pack_type").value == "rnb") {
        document.getElementById("result_2").innerHTML = "Writing manifest ...";
        uuids(false);
    }
    else {
        uuids(true);
    }
}

function uuids(write) {
    // The uuids are generated by this website.
    var url = "https://www.uuidgenerator.net/api/version4"
    // Nesting done statements ensures that the uuids are generated before moving on.
    $.get(
        url,
        function (data) {
            uuid_1 = data.substring(0, data.length - 2);
        }
    ).done(function() {
        $.get(
            url,
            function (data) {
                uuid_2 = data.substring(0, data.length - 2);
            }
        ).done(function() {
            if (write) {
                writeManifest("result");
            }
            else {
                uuids_2();
            }
        });
    });
}

function uuids_2() {
    var url = "https://www.uuidgenerator.net/api/version4"
    $.get(
        url,
        function (data) {
            uuid_3 = data.substring(0, data.length - 2);
        }
    ).done(function() {
        $.get(
            url,
            function (data) {
                uuid_4 = data.substring(0, data.length - 2);
            }
        ).done(function() {
            writeManifestDependent();
        });
    });
}

function writeManifest() {
    var pack_type = document.getElementById("pack_type").value;

    // Skin packs don't use a description.
    var description = "";
    if (pack_type != "skin_pack") {
        description = `\n        "description": "${document.getElementById("pack_desc").value}",`;
    }

    var new_horse = "";
    if (document.getElementById("new_horse_check").checked) {
        new_horse = ',\n        "min_engine_version": [1, 2, 6]'
    }

    document.getElementById("result").innerHTML = `{
    "format_version": 1,
    "header": {
        "name": "${document.getElementById("pack_name").value}",${description}
        "uuid": "${uuid_1}",
        "version": [0, 0, 1]${new_horse}
    },
    "modules": [
        {
            "type": "${pack_type}",
            "uuid": "${uuid_2}",
            "version": [0, 0, 1]
        }
    ]
}`;
}

function writeManifestDependent() {
    var pack_type = document.getElementById("pack_type").value;

    var new_horse = "";
    if (document.getElementById("new_horse_check").checked) {
        new_horse = ',\n        "min_engine_version": [1, 2, 6]'
    }

    document.getElementById("result").innerHTML = `{
    "format_version": 1,
    "header": {
        "name": "${document.getElementById("pack_name").value}",
        "description": "${document.getElementById("pack_desc").value}",
        "uuid": "${uuid_1}",
        "version": [0, 0, 1]${new_horse}
    },
    "modules": [
        {
            "type": "resources",
            "uuid": "${uuid_2}",
            "version": [0, 0, 1]
        }
    ],
    "dependencies": [
        {
            "uuid": "${uuid_3}",
            "version": [0, 0, 1]
        }
    ]
}`;

    document.getElementById("result_2").innerHTML = `{
    "format_version": 1,
    "header": {
        "name": "${document.getElementById("pack_name_2").value}",
        "description": "${document.getElementById("pack_desc_2").value}",
        "uuid": "${uuid_3}",
        "version": [0, 0, 1]
    },
    "modules": [
        {
            "type": "data",
            "uuid": "${uuid_4}",
            "version": [0, 0, 1]
        }
    ],
    "dependencies": [
        {
            "uuid": "${uuid_1}",
            "version": [0, 0, 1]
        }
    ]
}`;
}

// Disables the description input when a skin pack is chosen.
function enableSettings() {
    var pack = document.getElementById("pack_type").value;
    var pack_txt = document.getElementById("pack_name_txt");
    var desc_txt = document.getElementById("pack_desc_txt");

    if (pack == "skin_pack") {
        document.getElementById("pack_desc").disabled = true;
    }
    else {
        document.getElementById("pack_desc").disabled = false;
    }

    if (pack == "resources" || pack == "rnb") {
        document.getElementById("new_horse").hidden = false;
    }
    else {
        document.getElementById("new_horse").hidden = true;
        document.getElementById("new_horse_check").checked = false;
    }

    if (pack == "rnb") {
        document.getElementById("col-2").hidden = false;
        pack_txt.innerHTML = "Resource p" + pack_txt.innerHTML.substring(1);
        desc_txt.innerHTML = "Resource p" + desc_txt.innerHTML.substring(1);
    }
    else {
        document.getElementById("col-2").hidden = true;
        if (pack_txt.innerHTML.startsWith("Resource")) {
            pack_txt.innerHTML = "P" + pack_txt.innerHTML.substring(10);
            desc_txt.innerHTML = "P" + desc_txt.innerHTML.substring(10);
        }
    }
}